### ISSUE TITLE
Details presentation

### ISSUE THREAD

**Issue by filipandrei87** [yuriferretti/YFCardTransitions#1]
Hi,

Is there a way to make the details presentation frame smaller? I have quite a few details that I need to show so about 1/2 the screen height should be enough for me. Having a translucent background also would be a plus too.

Thanks

**Comment by yuriferretti-luizalabs** [comment]
@filipandrei87 when you talk about details presentation frame, are you talking about the view controller being presented? If so, this classes are just custom transitioning animation classes, so you could put any UIViewController´s subclass with your desired customizations as presented view controller
